name: package_chatbot
description: A new Flutter package project.
version: 0.0.1
author:
homepage: https://github.com/vietinfo/package_chatbot.git
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^2.0.8
  dio: ^4.0.0
  get: ^4.1.4
  extended_image: ^4.1.0
  intl: ^0.17.0
  url_launcher: ^6.0.3
  flutter_html: ^2.0.0
  flutter_tts: ^3.1.0
  map_launcher: ^2.0.0
  extended_image_library: ^3.1.0
  http: ^0.13.3
  rxdart: ^0.27.1
  flutter_spinkit: ^5.0.0
  location: ^4.1.1
  open_file: ^3.2.1
#  google_place: ^0.4.0
  popover: ^0.2.6+1
  percent_indicator: ^3.0.1
  top_snackbar_flutter: ^1.0.0

#  scroll_to_index: ^2.0.0
#  dropdownfield: ^1.0.3
#  speech_bubble: ^0.0.9
#  floating_action_bubble: 1.0.9```````
  speech_to_text_vi:
    git:
      url: https://github.com/vietinfo/speech_to_text_vi.git
      ref: 6c1d3c42b09df5f2deb3fc8ddd85a10fa62831fc




dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - assets/
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
